# Generated by Django 4.1.3 on 2022-11-26 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_alter_style_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='size',
            name='color',
        ),
        migrations.RemoveField(
            model_name='size',
            name='stock',
        ),
    ]
